{% set name = "modernize" %}
{% set version = "0.8.0" %}
{% set hash = "1672b4bb19a060a53dd0518cc8f70fc83591c7246e532223459f85d338c60f55" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - python-modernize = libmodernize.main:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - fissix
    - python

test:
  imports:
    - libmodernize
    - libmodernize.fixes

  commands:
    - python-modernize --help

about:
  home: https://github.com/python-modernize/python-modernize
  license: BSD 3-clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/python-modernize/python-modernize
  doc_url: http://python-modernize.readthedocs.io/
  summary: A hack on top of 2to3 for modernizing code for hybrid codebases.

extra:
  recipe-maintainers:
    - nicoddemus
