{% set name = "modernize" %}
{% set version = "0.6" %}
{% set hash_type = "sha256" %}
{% set hash = "e26c32c1bbf0f686f8c803691d8ffb4ddaaee1e60aa9bdf97257d80f2a5e4d29" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - python-modernize = libmodernize.main:main

  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - libmodernize
    - libmodernize.fixes

  commands:
    - python-modernize --help

about:
  home: https://github.com/python-modernize/python-modernize
  license: BSD 3-clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/python-modernize/python-modernize
  doc_url: http://python-modernize.readthedocs.io/
  summary: 'A hack on top of 2to3 for modernizing code for hybrid codebases.'

extra:
  recipe-maintainers:
    - nicoddemus
