{% set name = "modernize" %}
{% set version = "0.8.0" %}
{% set hash = "1672b4bb19a060a53dd0518cc8f70fc83591c7246e532223459f85d338c60f55" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - python-modernize = libmodernize.main:main

  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - fissix
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - libmodernize
    - libmodernize.fixes

  commands:
    - python-modernize --help

about:
  home: https://github.com/python-modernize/python-modernize
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  dev_url: https://github.com/python-modernize/python-modernize
  doc_url: http://python-modernize.readthedocs.io/
  summary: A hack on top of 2to3 for modernizing code for hybrid codebases.

extra:
  recipe-maintainers:
    - nicoddemus
