travis:
  secure:
    BINSTAR_TOKEN: PZHWmxldmwQgmRNNLqZ9tso0tp69A4/aR+uc3FOMCcAVVLYPXgap+KX6ezQpQK2PvHR4DWzanI/ysTXBy7llZWrfMfGuTRoLRBHcFW99zYgduR8JLRny2Ti09jgjqRqlkxvpldiV3HyG2RQEYFSM7HKergKTKIu5jgn4FgbmQUHff7Q5mptwlFN9SMVP3/QV7N01ONLdTsqzIZLY/3dCI9eBHIWNcIw+qTs6dAtAEww7XDzPF0Y1c+F2m5TRhVSs42a/dJnTLHgFzZCl9+tvofjp92SN898603HXpKmAKTh8OKQMOGn8OfrTCILhjXrxmii87dvkViADworFKfr6zD/urPcmDI5BnJZmWTvxozlkoTr7JLncB6QfZIYq7qzPye9xDM+mddqYZy2kXyXqlX+Fu+bHyeRqTxty+KGCi3m1qRiYhZwoIszMV8vnpx62P1Osq+U45pRxhDfK+6YxKZGdRKaz2/OSSb8zb74JN9JKm2yGV6JJeyyNMCIXsrmLloTeJm6U0uLr8Tj/cMIrr2z161jsvnYuAoc+Lduxiq4vQXr6HEy8kUi1vI3vWF4Q2PGGhd2qjZ8byUxwSwjRm/kNKfM8pYj1dDCc51UH/7NSZuDnA9lUi0YWZJuGmxzo+Mqr9kWBI9Af2amv3u0IB+98U8zbwtkCRBRmdtVi/rU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
