travis:
  secure:
    BINSTAR_TOKEN: Ptup6cHdxyRWlQO8i26hgYAMkLQIcNn2Cy96OT20kWdZuhA/cWUaQU/a8zNE9j+sQ66XxOJEC9oeTFDpU8Lqeg+AWLlgnLR5yhIJtz1aaLtwUHqGI7Vm5/0BRQvYeM/BUomjimN/PI22AR44wW2gLZ+4AsB71TGDwMHU+AE7DRDTbc6B+gMWbWuaNc/855z2MmOu7cTMm50bIc7i8jAj0aLLIxz4CrwqyfyvxLLs36/OMv76/sYIavlKWeJjCZ98r/RYB8ELuje1G53fq7kAFsVuXpyUmf4zfibCBj4sf+nnyvGjLoQEFEJIT3cetPozBK1l0qw/TZAhoUDEqbNkn9WUge5FBIO18KYSAFVXGQRFiTf73z4NDzFtkRYMDjZmxE4Jou/Nq5QeVRpRwcmSt9z77yFwPS4VTfKhqDmP7mPgLZY0Z0Hpae7M7FSZykyPWGxeLyydmGYoInnUS+ZNN1oPHspUU9uWafbvKI2cDaPjVxzJBjy9lsbWZX134E5KEE4uUPtfhRlrQpNm4k1a0unkZMEEhE62Xgp2T3LLnBsZT6rHfvqKIduy9e86sxKyl5mJLGF7F2zKr5JrOMw50ciObS0Pg3VprP01Yse4avCvUAwDlnsMS7Nkwl2rFUuwFaFZf12evYxmc5Z/2OirdzQBQms4KfP85C/Mx3gV6Vc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
